version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=your_database_url
      - SECRET_KEY=your_secret_key
  - HCAPTCHA_ENABLED=0 # Set to 1 to enforce captcha
  - HCAPTCHA_SECRET=your_hcaptcha_secret
    volumes:
      - ../backend:/app
    depends_on:
      - db

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=your_db_user
      - POSTGRES_PASSWORD=your_db_password
      - POSTGRES_DB=your_db_name
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: