- hosts: all
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - python3
          - python3-pip
          - docker.io
          - docker-compose
        state: present

    - name: Clone the VaultUpload repository
      git:
        repo: 'https://github.com/yourusername/VaultUpload.git'
        dest: /opt/VaultUpload
        version: main

    - name: Install Python dependencies
      pip:
        requirements: /opt/VaultUpload/backend/requirements.txt

    - name: Build Docker images
      command: docker-compose build
      args:
        chdir: /opt/VaultUpload/devops

    - name: Start Docker containers
      command: docker-compose up -d
      args:
        chdir: /opt/VaultUpload/devops

    - name: Ensure services are running
      command: docker ps
      register: docker_ps

    - debug:
        var: docker_ps.stdout_lines

    - name: Clean up old containers
      command: docker system prune -f

    - name: Check health of backend service
      uri:
        url: http://localhost:5000/health
        method: GET
        return_content: yes
      register: health_check

    - debug:
        var: health_check.content

    - name: Notify if backend service is not healthy
      fail:
        msg: "Backend service is not healthy!"
      when: health_check.status != 200